import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ContactBand } from "@/components/contact-band";
import { PageHero } from "@/components/page-hero";
import { SectionLabel } from "@/components/section-label";
import { primaryButtonClass, sectionClass, sectionHeadingClass } from "@/components/ui-classes";
import { allContent } from "@/content/site-data";

type ServiceDetail = { introTitle: string; intro: string; services: { title: string; text: string }[]; processTitle: string; process: string[]; readinessTitle: string; readiness: string; faqs: { question: string; answer: string }[] };

const serviceDetails: Record<string, ServiceDetail> = {
  "audit-assurance": { introTitle: "More than a report. A clearer view of risk.", intro: "Strong assurance brings discipline to financial reporting and perspective to the controls behind it. G12 Accounts approaches each engagement with independence, professional care and a practical understanding of how the business operates.", services: [{ title: "Audit & Assurance", text: "Independent audits that provide confidence in your financial statements while ensuring compliance with applicable regulations." }, { title: "Internal Audit", text: "Evaluate internal controls, identify operational risks and improve business processes through comprehensive internal audits." }, { title: "External Audit", text: "Professional external audits designed to meet statutory requirements and provide stakeholders with confidence in financial reporting." }, { title: "FTA Tax Audit Representation", text: "Expert guidance and representation through Federal Tax Authority audits, including documentation and responses." }], processTitle: "A disciplined path from planning to reporting.", process: ["Plan the engagement. Understand the business, reporting framework, risks and stakeholder expectations.", "Test the evidence. Perform focused procedures across financial information, transactions and controls.", "Resolve the findings. Discuss issues early, clarify evidence and agree practical actions where needed.", "Report with clarity. Deliver conclusions and observations in language decision-makers can use."], readinessTitle: "Make assurance more valuable.", readiness: "The strongest audits begin before fieldwork. Clear ownership, reconciled balances and accessible evidence reduce disruption and create more room for useful discussion.", faqs: [{ question: "What determines the scope of an audit engagement?", answer: "Scope depends on the entity, applicable requirements, reporting framework and engagement objective. These are clarified during planning." }, { question: "How should a business prepare for an audit?", answer: "Confirm ownership, close key reconciliations, organise supporting records and resolve unusual items before fieldwork begins." }, { question: "Can G12 Accounts support internal audit requirements?", answer: "Yes. Internal audit support can focus on selected processes, controls, risks or an agreed recurring plan." }] },
  "compliance-services": { introTitle: "Meet the requirement. Strengthen the business.", intro: "Compliance works best when it is built into normal operations rather than managed as a series of last-minute tasks. G12 Accounts helps businesses organise responsibilities, maintain reliable records and create a clear rhythm for recurring obligations.", services: [{ title: "Corporate Compliance & Governance", text: "Maintain compliance with UAE regulations while strengthening governance frameworks and internal policies." }, { title: "AML Compliance Advisory", text: "Implement effective Anti-Money Laundering policies and compliance procedures." }, { title: "UBO Declarations", text: "Prepare and submit Ultimate Beneficial Owner declarations in accordance with UAE regulations." }, { title: "Business Structuring", text: "Create efficient business structures that support long-term growth." }, { title: "Global Mobility Services", text: "Guidance for businesses managing international employees, executives and cross-border operations." }, { title: "Family Trust & Wealth Structuring", text: "Strategic trust and succession planning to protect and preserve family wealth." }], processTitle: "A practical system for staying ready.", process: ["Map the obligations. Identify recurring requirements, deadlines, information sources and responsible owners.", "Organise the records. Create a dependable structure for financial data, evidence, approvals and documentation.", "Build the controls. Introduce proportionate checks that make responsibilities visible and repeatable.", "Monitor and improve. Track completion, resolve changes and strengthen the process over time."], readinessTitle: "Make compliance part of the rhythm.", readiness: "A clear calendar, accountable owners and reliable supporting records turn compliance from an interruption into a controlled business process.", faqs: [{ question: "What does ongoing compliance support include?", answer: "The scope can include accounting records, reporting, calendars, documentation, controls and advice on recurring obligations." }, { question: "Can support be tailored to our internal finance team?", answer: "Yes. G12 Accounts can complement the existing team, take ownership of selected activities or provide review and oversight." }, { question: "Can the compliance scope change as the business grows?", answer: "Yes. The support model can be reviewed as entities, activities, reporting needs and internal capabilities change." }] },
  "corporate-tax": { introTitle: "Compliance is essential. Clarity creates confidence.", intro: "UAE corporate tax affects more than the annual return. It touches financial records, business structures, related-party transactions and the way key decisions are documented. G12 Accounts helps businesses understand what applies, organise the right evidence and build a dependable compliance process.", services: [{ title: "Corporate Tax Advisory", text: "Expert guidance on UAE corporate tax regulations and how they apply to your business." }, { title: "Tax Compliance", text: "Prepare and manage corporate tax obligations, ensuring timely and accurate compliance." }, { title: "Tax & Accounting Services", text: "Integrated accounting and tax solutions that maintain accurate records and support efficient tax management." }, { title: "Direct Tax Consultancy", text: "Strategic advice on tax planning, business transactions and regulatory requirements." }], processTitle: "A clear path from scope to submission.", process: ["Understand the business. Map entities, activities, transactions, systems and current responsibilities.", "Assess the position. Identify requirements, exposures, documentation gaps and available actions.", "Prepare the evidence. Build calculations, schedules, records and the review trail needed for compliance.", "File and stay ready. Complete the submission and translate lessons into stronger recurring controls."], readinessTitle: "Make readiness part of how you operate.", readiness: "The strongest compliance position is built throughout the year. Clear ownership, reliable reconciliations and records created alongside decisions make the annual filing easier to support.", faqs: [{ question: "Who needs to consider UAE corporate tax registration?", answer: "Registration requirements depend on the entity, activities and applicable legislation. Each legal entity and business arrangement should be reviewed against current rules." }, { question: "When should a business start preparing for its return?", answer: "Preparation should begin well before the filing deadline. Recurring reconciliations and early review of unusual transactions make the process more reliable." }, { question: "Can G12 Accounts provide ongoing corporate tax support?", answer: "Yes. Support can be structured around a filing, readiness review, transaction or an ongoing advisory and compliance requirement." }] },
  "customs-services": { introTitle: "Reduce friction. Strengthen control.", intro: "Customs decisions affect cost, timing, documentation and operational risk. G12 Accounts helps businesses understand their obligations, improve the evidence behind declarations and build clearer processes across import and export activity.", services: [{ title: "Customs Audit & Duty Optimisation", text: "Review customs procedures, identify compliance risks and uncover opportunities to optimise duty costs." }, { title: "Customs Registration & Import Code", text: "Assistance with customs registration and the import codes needed to begin trading smoothly." }, { title: "Customs Refund & Duty Recovery", text: "Identify eligible customs refunds and recover duties where applicable." }, { title: "Customs Health Check", text: "Review procedures to identify gaps, strengthen compliance and improve operational efficiency." }, { title: "Customs Exemption & Duty Relief", text: "Advice on available customs exemptions and duty relief programmes." }], processTitle: "From transaction flow to clearer control.", process: ["Map the trade flow. Understand products, routes, parties, responsibilities, systems and documentation.", "Review the treatment. Assess classification, valuation, origin and supporting evidence.", "Resolve the gaps. Prioritise corrections, documentation needs and process improvements.", "Embed the controls. Build recurring checks around declarations, records and business changes."], readinessTitle: "Keep documentation close to the transaction.", readiness: "Clear product data, consistent instructions and accessible commercial evidence make customs positions easier to explain and operations easier to manage.", faqs: [{ question: "Why is tariff classification important?", answer: "Classification can affect duty treatment, documentation and controls. The selected code should be supported by accurate product information." }, { question: "Can G12 Accounts perform a customs health check?", answer: "Yes. A focused review can assess selected transactions, classifications, documentation and recurring controls." }, { question: "When should customs advice be considered?", answer: "Advice is particularly useful when products, supply chains, counterparties, pricing arrangements or operating models change." }] },
  "international-tax": { introTitle: "See the whole structure. Understand the impact.", intro: "Cross-border growth creates connected tax questions across entities, transactions, people and jurisdictions. G12 Accounts helps businesses frame those questions early, coordinate the right analysis and document decisions with greater confidence.", services: [{ title: "Transfer Pricing Advisory", text: "Ensure intercompany transactions comply with international regulations and arm’s-length pricing requirements." }, { title: "Master File Maintenance", text: "Prepare and maintain transfer-pricing documentation to meet regulatory requirements." }, { title: "Double Taxation Relief", text: "Help benefit from applicable Double Taxation Avoidance Agreements." }, { title: "Foreign Tax Credit Advisory", text: "Guidance on claiming eligible foreign tax credits and optimising international tax position." }], processTitle: "Connect the facts before choosing the structure.", process: ["Understand the objective. Clarify the commercial plan, jurisdictions, entities, transactions and timeline.", "Map the tax questions. Identify connected issues, assumptions, dependencies and information needs.", "Evaluate the options. Compare practical approaches alongside governance and documentation requirements.", "Implement with evidence. Support the chosen approach and maintain a clear record of the rationale."], readinessTitle: "Consider tax before the model is fixed.", readiness: "International tax is easier to manage when it is considered alongside the commercial plan, contracts, people and transaction flows—not after implementation.", faqs: [{ question: "When should international tax advice be sought?", answer: "Ideally before entering a jurisdiction, changing a structure, signing material agreements or implementing new related-party transactions." }, { question: "How does transfer pricing connect to international tax?", answer: "Transfer pricing considers transactions between related parties and is often central to how cross-border operating models are documented." }, { question: "Can G12 Accounts coordinate advice across jurisdictions?", answer: "G12 Accounts can help frame the issues, coordinate inputs and keep the overall position connected to the UAE business." }] },
  vat: { introTitle: "Every transaction matters. Every return needs support.", intro: "VAT is embedded in everyday sales, purchases, systems and documents. G12 Accounts helps businesses understand transaction treatment, maintain the right evidence and build a filing process that is accurate, timely and reviewable.", services: [{ title: "VAT Registration", text: "Handle the complete VAT registration process accurately and efficiently." }, { title: "VAT Return Filing", text: "Prepare and submit VAT returns on time, reducing the risk of errors and penalties." }, { title: "VAT Consultancy & Advisory", text: "Guidance on VAT regulations, transactions and tax planning." }, { title: "VAT Compliance Audit", text: "Review VAT processes, identify potential risks and recommend improvements." }, { title: "VAT Refund Services", text: "Prepare eligible VAT refund claims with supporting documentation in place." }], processTitle: "From transaction data to a supported return.", process: ["Understand the activity. Map supplies, purchases, systems, documents and VAT responsibilities.", "Reconcile the data. Connect return balances to accounting records and investigate material differences.", "Review the treatment. Assess selected transactions, evidence and adjustments before submission.", "File and improve. Complete the return and strengthen recurring checks for the next period."], readinessTitle: "Build the evidence as you trade.", readiness: "Accurate tax invoices, consistent transaction coding and regular reconciliations make VAT returns easier to prepare and positions easier to support.", faqs: [{ question: "How do we know whether VAT registration is required?", answer: "Registration depends on business activities and current UAE requirements. The entity and relevant supplies should be reviewed against the applicable rules." }, { question: "What should be reviewed before filing a VAT return?", answer: "Key checks usually include reconciliations, transaction coding, supporting documents, adjustments and unusual or material items." }, { question: "Can G12 Accounts support one-off VAT questions?", answer: "Yes. Advice can address a specific transaction, contract, business change, review or authority-related information request." }] },
};

export function generateStaticParams() { return allContent.map(({ slug }) => ({ slug })); }
export function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { return params.then(({ slug }) => { const page = allContent.find((item) => item.slug === slug); return page ? { title: page.label, description: page.description } : {}; }); }

export default async function ContentPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const page = allContent.find((item) => item.slug === slug);
  if (!page) notFound();
  const detail = serviceDetails[slug];
  if (!detail) return <PostPage page={page} />;
  return <main>
    <PageHero index="01" label={`Expertise / ${page.label}`} title={<>{page.title}<br /><em>{page.emphasis}</em></>} description={page.description} />
    <section className={sectionClass}><SectionLabel number="01">{page.label} advisory</SectionLabel><div className="mt-[60px] mb-[55px] grid items-start gap-[clamp(50px,9vw,140px)] min-[801px]:ml-[clamp(0px,7vw,110px)] min-[801px]:grid-cols-[1fr_.72fr]"><h2 className={sectionHeadingClass}>{detail.introTitle}</h2><p className="m-0 text-base leading-[1.85] text-[#66718a]">{detail.intro}</p></div>{page.image && <div className="relative my-[50px] aspect-[2.35/1] w-full overflow-hidden bg-g12-navy max-[680px]:aspect-[4/3]"><Image className="object-cover" src={page.image} alt={`${page.label} advisory`} fill sizes="(max-width: 800px) 100vw, 1240px" /></div>}</section>
    <section className={`${sectionClass} bg-white shadow-[0_0_0_100vmax_#fff] [clip-path:inset(0_-100vmax)]`}><SectionLabel number="02">How we help</SectionLabel><div className="mt-[58px] mb-[70px] grid items-end gap-20 min-[801px]:ml-[clamp(0px,7vw,110px)] min-[801px]:grid-cols-[1fr_.6fr] max-[800px]:gap-[25px]"><h2 className="m-0 text-[clamp(42px,5vw,70px)] leading-[.98] font-normal tracking-[-.05em]">The support you need,<br /><em>at the right stage.</em></h2><p className="m-0 max-w-[360px] text-[15px] leading-[1.8] text-[#66718a]">Specialist support that keeps the work connected to your business, records and decisions.</p></div><div className="grid border-t border-[#07152f29] min-[801px]:grid-cols-2">{detail.services.map((item, index) => <article className="min-h-[275px] border-b border-[#07152f29] py-[34px] pr-[clamp(25px,4vw,60px)] max-[800px]:min-h-0 max-[800px]:py-[30px] max-[800px]:pr-0 min-[801px]:border-r min-[801px]:border-[#07152f29] min-[801px]:even:border-r-0 min-[801px]:even:pr-0 min-[801px]:even:pl-[clamp(25px,4vw,60px)]" key={item.title}><span className="text-[9px] font-bold tracking-[.16em] text-g12-blue">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-[72px] mb-4 text-[clamp(25px,2.4vw,34px)] leading-[1.05] font-medium max-[800px]:mt-[45px]">{item.title}</h3><p className="m-0 max-w-[440px] text-sm leading-[1.75] text-[#66718a]">{item.text}</p></article>)}</div></section>
    <section className={`${sectionClass} bg-[#f3f6fc] pb-[130px] shadow-[0_0_0_100vmax_#f3f6fc] [clip-path:inset(0_-100vmax)]`}><SectionLabel number="03">Our process</SectionLabel><h2 className="mt-[58px] mb-[60px] max-w-[650px] text-[clamp(42px,5vw,70px)] leading-[.98] font-normal tracking-[-.05em] min-[801px]:ml-[clamp(0px,7vw,110px)]">{detail.processTitle}</h2><div className="grid border-t border-[#ccd7eb] min-[801px]:grid-cols-4">{detail.process.map((step, index) => <article className="min-h-[215px] border-[#ccd7eb] py-[30px] pr-[30px] max-[800px]:min-h-0 max-[800px]:border-b max-[800px]:py-7 max-[800px]:pr-0 min-[801px]:border-r min-[801px]:last:border-r-0 min-[801px]:not-first:pl-[30px]" key={step}><span className="text-[9px] font-bold tracking-[.16em] text-g12-blue">{String(index + 1).padStart(2, "0")}</span><p className="mt-[62px] text-sm leading-[1.7] text-[#66718a] max-[800px]:mt-[35px]">{step}</p></article>)}</div></section>
    <section className="grid min-h-[500px] place-items-center bg-[linear-gradient(130deg,#06142d,#123d84)] px-6 py-[95px] text-center text-white min-[801px]:min-h-[560px]"><div className="max-w-[790px]"><div className="flex justify-center"><SectionLabel number="04" light>{page.label} readiness</SectionLabel></div><h2 className="mt-12 mb-[26px] text-[clamp(45px,6vw,78px)] leading-[.95] font-normal tracking-[-.055em]">{detail.readinessTitle}</h2><p className="mx-auto mb-10 max-w-[610px] text-base leading-[1.85] text-white/80">{detail.readiness}</p><Link className={primaryButtonClass} href="/contact-us/">Discuss your requirement <span>↗</span></Link></div></section>
    <section className={`${sectionClass} bg-white shadow-[0_0_0_100vmax_#fff] [clip-path:inset(0_-100vmax)]`}><SectionLabel number="05">Common questions</SectionLabel><div className="mt-[58px] mb-[70px] grid items-end gap-20 min-[801px]:ml-[clamp(0px,7vw,110px)] min-[801px]:grid-cols-[1fr_.6fr] max-[800px]:gap-[25px]"><h2 className="m-0 text-[clamp(42px,5vw,70px)] leading-[.98] font-normal tracking-[-.05em]">{page.label},<br /><em>made clearer.</em></h2><p className="m-0 max-w-[360px] text-[15px] leading-[1.8] text-[#66718a]">Specific requirements depend on each business and should be reviewed individually.</p></div><div className="border-t border-[#07152f29] min-[801px]:ml-[clamp(0px,7vw,110px)]">{detail.faqs.map((faq) => <details className="border-b border-[#07152f29]" key={faq.question}><summary className="flex cursor-pointer list-none justify-between gap-[30px] py-[25px] text-lg font-medium [&::-webkit-details-marker]:hidden">{faq.question}<span className="text-[25px] leading-[.75] font-normal text-g12-blue group-open:rotate-45">+</span></summary><p className="m-0 max-w-[720px] pr-[50px] pb-[25px] text-sm leading-[1.8] text-[#66718a]">{faq.answer}</p></details>)}</div></section>
    <ContactBand />
  </main>;
}

function PostPage({ page }: { page: (typeof allContent)[number] }) { return <main><PageHero index="07" label={page.label} title={<>{page.title}<br /><em>{page.emphasis}</em></>} description={page.description} /><section className={sectionClass}><SectionLabel number="01">G12 perspective</SectionLabel><div className="mt-[60px] mb-[85px] grid items-start gap-[clamp(50px,9vw,140px)] min-[801px]:ml-[clamp(0px,7vw,110px)] min-[801px]:grid-cols-[1fr_.72fr]"><h2 className={sectionHeadingClass}>Useful perspective for clearer decisions.</h2><div>{page.body.map((paragraph) => <p className="mb-[22px] text-[15px] leading-[1.85] text-[#66718a]" key={paragraph}>{paragraph}</p>)}</div></div></section><ContactBand /></main>; }
