import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { PageHero } from "@/components/page-hero";
import { SectionLabel } from "@/components/section-label";
import { primaryButtonClass, sectionClass } from "@/components/ui-classes";

export const metadata: Metadata = { title: "Expertise", description: "Meet the senior accounting, tax, audit and advisory specialists at G12 Accounts." };

const experts = [
  { name: "Basit Habib, CA", role: "Director | CFO Advisory & Corporate Tax", image: "/images/live/Account-Employees-1.jpeg", bio: "With over 18 years of international experience across the UAE, Pakistan, the USA and Africa, Basit specialises in corporate tax, VAT advisory, CFO services and corporate governance. He works closely with business owners and leadership teams to strengthen financial performance, improve governance and support strategic growth." },
  { name: "Ateeq Ur Rehman, FCMA", role: "Finance & Strategic Advisory", image: "/images/live/Account-Employees-2.jpeg", bio: "A results-driven finance professional with 18+ years of experience, Ateeq specialises in financial planning, budgeting, treasury, ERP implementation and business process optimisation. His expertise helps businesses improve operational efficiency while making informed financial decisions." },
  { name: "Muhammad Usama", role: "Financial Reporting & Tax Specialist", image: "/images/live/Account-Employees-3.jpeg", bio: "With over 10 years of experience in accounting and financial operations, Muhammad specialises in financial reporting, cash flow management, VAT, corporate tax and audit coordination. His attention to detail helps businesses maintain accurate financial records and remain fully compliant." },
];

export default function ExpertisePage() {
  return <main>
    <PageHero index="01" label="Our experts" title={<>Expertise is<br /><em>personal.</em></>} description="Senior specialists stay close to the work, the conversation and the decisions that move your business forward." />
    <section className={`${sectionClass} bg-white shadow-[0_0_0_100vmax_#fff] [clip-path:inset(0_-100vmax)]`}><SectionLabel number="01">The team</SectionLabel><div className="mt-[58px] mb-[70px] grid items-end gap-20 min-[801px]:ml-[clamp(0px,7vw,110px)] min-[801px]:grid-cols-[1fr_.6fr] max-[800px]:gap-[25px]"><h2 className="m-0 text-[clamp(42px,5vw,70px)] leading-[.98] font-normal tracking-[-.05em]">The right expertise,<br /><em>directly involved.</em></h2><p className="m-0 max-w-[360px] text-[15px] leading-[1.8] text-[#66718a]">Each specialist brings practical experience and stays connected to the work they lead.</p></div><div className="grid gap-px bg-[#07152f29] min-[801px]:grid-cols-3">{experts.map((expert, index) => <article className="bg-white" key={expert.name}><div className="relative aspect-[4/4.4] overflow-hidden bg-[#dfe8f8]"><Image className="object-cover object-top" src={expert.image} alt={expert.name} fill sizes="(max-width: 800px) 100vw, 33vw" /></div><div className="min-h-[400px] px-7 pt-7 pb-[45px] max-[800px]:min-h-0 max-[800px]:px-6"><span className="text-[9px] font-bold uppercase tracking-[.14em] text-g12-blue">{String(index + 1).padStart(2, "0")} / G12 Accounts</span><h2 className="mt-[55px] mb-2.5 text-[clamp(28px,2.7vw,40px)] leading-[1.02] font-normal max-[800px]:mt-10">{expert.name}</h2><h3 className="mb-[25px] text-[11px] leading-[1.5] font-semibold uppercase tracking-[.04em] text-g12-blue">{expert.role}</h3><p className="m-0 text-sm leading-[1.8] text-[#66718a]">{expert.bio}</p></div></article>)}</div></section>
    <section className="grid min-h-[540px] place-items-center bg-[radial-gradient(circle_at_80%_45%,#173c7c_0%,#06142d_55%)] px-6 py-[110px] text-center text-white min-[801px]:min-h-[620px]"><div className="max-w-[800px]"><div className="flex justify-center"><SectionLabel number="02" light>One connected team</SectionLabel></div><h2 className="mt-[50px] mb-[27px] text-[clamp(48px,6.5vw,84px)] leading-[.93] font-normal tracking-[-.06em] [&_em]:text-[#a9c0f8]">Specialists who see<br />the <em>whole picture.</em></h2><p className="mx-auto mb-[42px] max-w-[620px] leading-[1.85] text-white/75">Our experts work across disciplines, bringing tax, audit, accounting and compliance perspectives together when the issue demands more than one answer.</p><Link className={primaryButtonClass} href="/contact-us/">Start a conversation <span>↗</span></Link></div></section>
  </main>;
}
