import type { Metadata } from "next";
import { ContactBand } from "@/components/contact-band";
import { PageHero } from "@/components/page-hero";
import { SectionLabel } from "@/components/section-label";

export const metadata:Metadata={title:"About Us",description:"Meet G12 Accounts, a UAE-focused accounting, tax and advisory firm built for clear decisions and sustainable business progress.",alternates:{canonical:"/about-us/"},openGraph:{title:"About G12 Accounts",description:"Senior-led accounting, tax and advisory expertise for UAE businesses.",url:"/about-us/"}};

const strengths=[{title:"Senior-led",text:"Experienced specialists stay close to the work and the decisions behind it."},{title:"UAE-focused",text:"Local regulatory knowledge shaped around the realities of doing business here."},{title:"Commercially aware",text:"Advice designed around business momentum, not compliance in isolation."}];
const principles=[{title:"Clarity first.",text:"We turn technical complexity into language, priorities and actions that make sense."},{title:"Personally involved.",text:"Senior expertise stays connected, responsive and accountable from start to finish."},{title:"Progress minded.",text:"Every engagement looks beyond the immediate requirement toward what the business needs next."}];

export default function AboutPage(){return <main><PageHero index="02" label="About" title={<>Clarity that moves<br/>business <em>forward.</em></>} description="We bring accounting discipline, tax expertise and commercial perspective together—so every financial decision has a clearer direction."/><section className="section inner-intro"><SectionLabel number="01">Who we are</SectionLabel><div className="inner-intro__grid"><h2>Built for decisions,<br/>not just <em>deadlines.</em></h2><div><p>G12 Accounts is a UAE-focused accounting, tax and advisory firm for businesses that expect more from their financial partner. We help leaders understand the numbers, meet their obligations and move with greater confidence.</p><p>Our work connects day-to-day compliance with the bigger commercial picture. The result is advice that is technically sound, clearly communicated and useful when decisions matter.</p></div></div><blockquote className="about-quote">Good financial advice should do more than explain the past. It should make the next move clearer.</blockquote><div className="feature-row">{strengths.map((item,index)=><article key={item.title}><span>0{index+1}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section><section className="section principles"><SectionLabel number="02">How we work</SectionLabel><h2>Three principles.<br/>One clearer <em>standard.</em></h2><div className="principle-grid">{principles.map((item,index)=><article key={item.title}><span>0{index+1}</span><i>↗</i><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section><section className="group-section"><div><SectionLabel number="03" light>The wider perspective</SectionLabel><h2>Independent expertise.<br/>Part of something <em>bigger.</em></h2><p>As a G12 Group company, we combine specialist accounting and tax capability with a broader understanding of how ambitious businesses grow, operate and transform.</p><a className="button button--outline" href="https://g12.ae/" target="_blank" rel="noreferrer">Discover G12 Group <span>↗</span></a></div><span aria-hidden="true">G12</span></section><ContactBand/></main>}
