import type { Metadata } from "next";
import Image from "next/image";
import { PageHero } from "@/components/page-hero";
import { ContactBand } from "@/components/contact-band";
import { Action, Eyebrow } from "@/components/editorial";
export const metadata: Metadata = { title: "About Us", description: "Senior-led accounting, tax and advisory expertise for UAE businesses.", alternates: { canonical: "/about-us/" } };
export default function AboutPage(){return <main><PageHero index="01" label="Our perspective" title={<>Built for decisions.<br /><em>Beyond deadlines.</em></>} description="We bring accounting discipline, tax expertise and commercial perspective together—so every financial decision has a clearer direction." />
<section className="about-story editorial-wrap"><div className="about-visual"><Image src="/images/live/perspective-advisory.jpg" alt="Financial advisors working together" fill sizes="(max-width:800px) 100vw, 45vw" /><span>Independent expertise.<br />Personally involved.</span></div><div data-reveal><Eyebrow>Our reason for being</Eyebrow><h2>Better questions.<br /><em>Clearer answers.</em></h2><p>G12 Accounts is a UAE-focused accounting, tax and advisory firm for businesses that expect more from their financial partner. We help leaders understand the numbers, meet their obligations and move with greater confidence.</p><p>Our work connects day-to-day compliance with the bigger commercial picture. The result is advice that is technically sound, clearly communicated and useful when decisions matter.</p><Action href="/expertise/">Meet the people behind G12</Action></div></section>
<section className="belief-section"><div className="editorial-wrap"><Eyebrow>What we believe</Eyebrow><h2 data-reveal>Good financial advice<br />should make your<br /><em>next move clearer.</em></h2><div className="belief-facts"><div><strong>18+</strong><span>Years of experience</span></div><div><strong>360°</strong><span>A connected perspective</span></div><div><strong>UAE</strong><span>Local knowledge. Wider thinking.</span></div></div></div></section>
<section className="editorial-wrap principles"><Eyebrow>How we work</Eyebrow><div>{[["Clarity first.","We turn technical complexity into language, priorities and actions that make sense."],["Personally involved.","Senior expertise stays connected, responsive and accountable from start to finish."],["Progress minded.","Every engagement looks beyond the immediate requirement toward what the business needs next."]].map(([title,text],i)=><article data-reveal key={title}><small>0{i+1}</small><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="group-section editorial-wrap"><Eyebrow>The wider perspective</Eyebrow><h2>Specialist thinking.<br /><em>Collective strength.</em></h2><p>As a G12 Group company, we combine specialist accounting and tax capability with a broader understanding of how ambitious businesses grow, operate and transform.</p><Action href="https://g12.ae/">Discover G12 Group</Action></section><ContactBand /></main>;}
