import Image from "next/image";
import Link from "next/link";
import { ContactBand } from "@/components/contact-band";
import { ServiceAccordion, type Service } from "@/components/service-accordion";
import { SectionLabel } from "@/components/section-label";
import { outlineButtonClass, primaryButtonClass, sectionClass, textLinkClass } from "@/components/ui-classes";

const services: Service[] = [
  { title: "Corporate Tax", description: "Strategic corporate tax advisory and compliance services tailored to evolving UAE tax regulations.", items: ["Tax registration & compliance", "Impact assessment", "Transfer pricing support"], href: "https://g12accounts.ae/corporate-tax/" },
  { title: "Audit & Assurance", description: "Independent audit services that strengthen financial transparency, accuracy and regulatory confidence.", items: ["Statutory audit", "Internal audit", "Financial review"], href: "https://g12accounts.ae/audit-assurance/" },
  { title: "VAT Services", description: "End-to-end VAT registration, filing, compliance and advisory that keeps your business ready.", items: ["VAT registration", "Return filing", "Voluntary disclosure"], href: "https://g12accounts.ae/vat/" },
  { title: "International Tax", description: "Cross-border tax planning and advisory that supports global operations with clarity and confidence.", items: ["Cross-border structuring", "Tax treaty advisory", "Global compliance"], href: "https://g12accounts.ae/international-tax/" },
  { title: "Customs Services", description: "Practical customs solutions that simplify cross-border trade, optimise duties and reduce risk.", items: ["Customs advisory", "Duty optimisation", "Import and export support"], href: "https://g12accounts.ae/customs-services/" },
  { title: "Compliance", description: "Clear governance and regulatory support that helps your business meet its obligations with confidence.", items: ["Corporate governance", "Regulatory support", "Compliance reviews"], href: "https://g12accounts.ae/compliance-services/" },
];

const insights = [
  { category: "Corporate Tax", time: "2 min read", title: "Beyond compliance: building a corporate tax strategy that supports growth", href: "https://g12accounts.ae/corporate-tax-strategy-that-supports-growth/" },
  { category: "VAT", time: "1 min read", title: "Five VAT risks growing businesses often overlook", href: "https://g12accounts.ae/five-vat-risks-growing-businesses-overlook/" },
  { category: "Advisory", time: "1 min read", title: "What better management reporting can unlock", href: "https://g12accounts.ae/what-better-management-reporting-can-unlock/" },
  { category: "International Tax", time: "1 min read", title: "Cross-border growth: the questions to ask first", href: "https://g12accounts.ae/cross-border-growth-questions-to-ask-first/" },
];

const structuredData = { "@context": "https://schema.org", "@type": "ProfessionalService", name: "G12 Accounts", url: "https://g12accounts.ae/", description: "Accounting, tax, audit and strategic advisory for businesses building their future in the UAE.", email: "finance@g12.ae", telephone: "+97145706451", areaServed: { "@type": "Country", name: "United Arab Emirates" }, address: { "@type": "PostalAddress", addressLocality: "Dubai", addressCountry: "AE" }, parentOrganization: { "@type": "Organization", name: "G12 Group", url: "https://g12.ae/" } };

export default function Home() {
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} /><main>
    <section className="relative h-[min(1040px,100svh)] min-h-[780px] overflow-hidden bg-g12-navy text-white" aria-labelledby="hero-title">
      <Image data-parallax className="scale-[1.06] object-cover object-center max-[680px]:object-[67%_center]" src="/images/g12-future-hero.png" alt="Abstract glass architecture flowing toward the Dubai skyline" fill priority sizes="100vw" />
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(2,8,22,.98)_0%,rgba(3,11,28,.92)_34%,rgba(4,14,34,.32)_62%,rgba(2,8,22,.08)),linear-gradient(0deg,rgba(2,8,22,.8),transparent_52%)] max-[680px]:bg-[linear-gradient(90deg,#020816f7,#04102f8f),linear-gradient(0deg,#020816e8,transparent_58%)]" />
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_48%,transparent_0_18%,rgba(100,141,240,.13)_18.2%_18.5%,transparent_18.7%_26%,rgba(214,164,86,.13)_26.2%_26.4%,transparent_26.6%)]" aria-hidden="true" />
      <div className="absolute inset-x-0 top-[88px] bottom-0 bg-[linear-gradient(90deg,transparent_calc(25%_-_1px),#ffffff14_25%,transparent_calc(25%_+_1px),transparent_calc(50%_-_1px),#ffffff14_50%,transparent_calc(50%_+_1px),transparent_calc(75%_-_1px),#ffffff14_75%,transparent_calc(75%_+_1px))] max-[680px]:bg-[linear-gradient(90deg,transparent_calc(50%_-_1px),#ffffff14_50%,transparent_calc(50%_+_1px))]" aria-hidden="true" />
      <div className="absolute top-1/2 left-[max(24px,calc((100vw-1240px)/2))] z-10 w-[min(690px,58vw)] -translate-y-[42%] max-[1080px]:w-[calc(100%-48px)] max-[980px]:top-[46%]">
        <div data-hero-reveal className="flex items-center gap-[13px] text-[10px] font-semibold uppercase tracking-[.2em] max-[680px]:text-[8px] max-[680px]:tracking-[.16em]"><span className="h-px w-[30px] bg-g12-gold" />Financial clarity for ambitious businesses</div>
        <h1 data-hero-reveal id="hero-title" className="mt-[30px] mb-[26px] text-[clamp(64px,7vw,108px)] leading-[.87] font-medium tracking-[-.065em] max-[980px]:text-[clamp(55px,11vw,82px)] max-[680px]:mt-6 max-[680px]:text-[clamp(51px,14vw,68px)] max-[680px]:leading-[.92] [&_em]:text-[#a9c0f8]">Precision behind<br /><em>every decision.</em></h1>
        <p data-hero-reveal className="w-[min(540px,100%)] text-[17px] leading-[1.7] text-white/75 max-[680px]:text-[15px]">Accounting, tax, audit and strategic advisory for businesses building their future in the UAE.</p>
        <div data-hero-reveal className="mt-11 flex items-center gap-10 max-[680px]:mt-8 max-[680px]:flex-col max-[680px]:items-start max-[680px]:gap-[25px]"><Link className={primaryButtonClass} href="/contact-us/">Start a conversation <span>↗</span></Link><Link className={`${textLinkClass} border-white/[.35]`} href="#expertise">Explore our expertise <span>↓</span></Link></div>
      </div>
      <div data-hero-panel className="absolute right-[max(38px,calc((100vw-1240px)/2))] top-[24%] z-10 hidden items-center gap-4 min-[1081px]:flex"><span className="relative grid size-14 place-items-center rounded-full border border-white/35"><i className="absolute size-2 animate-ping rounded-full bg-g12-gold" /><i className="size-2 rounded-full bg-g12-gold" /></span><span className="text-[9px] uppercase leading-[1.7] tracking-[.18em] text-white/65">One connected view<br />of what comes next</span></div>
      <div className="absolute right-[max(24px,calc((100vw-1240px)/2))] bottom-[64px] z-10 flex items-center gap-[18px] max-[1080px]:bottom-[58px] max-[680px]:right-auto max-[680px]:bottom-[30px] max-[680px]:left-6"><strong data-count="18" data-suffix="+" className="font-serif text-[56px] leading-none max-[680px]:text-[42px]">18+</strong><span className="text-[10px] leading-[1.6] uppercase tracking-[.11em] text-white/70">Years of<br />advisory experience</span></div>
      <span className="absolute top-1/2 right-[22px] z-10 [writing-mode:vertical-rl] text-[8px] uppercase tracking-[.25em] max-[980px]:hidden">Dubai · United Arab Emirates</span>
      <Link className="absolute bottom-[50px] left-1/2 z-10 flex -translate-x-1/2 items-center gap-2.5 text-[9px] uppercase tracking-[.16em] max-[980px]:hidden" href="#about"><span className="grid size-8 place-items-center rounded-full border border-white/[.35]">↓</span> Discover</Link>
    </section>
    <section className="relative overflow-hidden bg-white py-7" aria-label="Key capabilities"><div className="flex w-max animate-[marquee_24s_linear_infinite] items-center gap-9 whitespace-nowrap text-[clamp(18px,2vw,30px)] font-medium tracking-[-.03em] text-g12-navy"><span className="text-[10px] uppercase tracking-[.18em] text-[#66718a]">One trusted partner across</span>{["Accounting", "Tax", "Audit", "Advisory", "Compliance", "Accounting", "Tax", "Audit", "Advisory", "Compliance"].map((item,index)=><span className="flex items-center gap-9" key={`${item}-${index}`}><i className="size-1.5 rounded-full bg-g12-gold" />{item}</span>)}</div></section>
    <section className={sectionClass} id="about"><div data-reveal><SectionLabel number="01">Who we are</SectionLabel></div><div data-reveal className="mt-[62px] mb-[110px] ml-[clamp(0px,8vw,130px)] grid items-end gap-[clamp(50px,9vw,140px)] min-[981px]:grid-cols-[1.5fr_.65fr] max-[980px]:ml-0 max-[680px]:mt-[45px] max-[680px]:mb-[70px] max-[680px]:gap-[30px]"><h2>Your finances should do more than meet requirements. They should <em>move your business forward.</em></h2><div><p className="mb-[34px] text-[15px] leading-[1.8] text-[#66718a]">We combine technical expertise with practical business insight to help UAE companies stay compliant, improve performance and plan for sustainable growth.</p><Link className={textLinkClass} href="/about-us/">Meet your advisory partner <span>↗</span></Link></div></div><div data-reveal className="grid gap-12 max-[680px]:grid-cols-1 min-[681px]:grid-cols-3"><div className="flex items-end gap-4"><strong className="font-serif text-[clamp(55px,6vw,82px)] leading-[.85]"><span data-count="18">18</span><sup className="font-sans text-2xl leading-none text-g12-blue">+</sup></strong><span className="max-w-[100px] text-[9px] leading-[1.5] uppercase tracking-[.1em] text-[#66718a]">Years of experience</span></div><div className="flex items-end gap-4 min-[681px]:mt-12"><strong data-count="7" className="font-serif text-[clamp(55px,6vw,82px)] leading-[.85]">7</strong><span className="max-w-[100px] text-[9px] leading-[1.5] uppercase tracking-[.1em] text-[#66718a]">Integrated disciplines</span></div><div className="flex items-end gap-4"><strong className="font-serif text-[clamp(55px,6vw,82px)] leading-[.85]"><span data-count="360">360</span><sup className="font-sans text-2xl leading-none text-g12-blue">°</sup></strong><span className="max-w-[100px] text-[9px] leading-[1.5] uppercase tracking-[.1em] text-[#66718a]">Financial perspective</span></div></div></section>
    <section className={`${sectionClass} bg-white shadow-[0_0_0_100vmax_#fff] [clip-path:inset(0_-100vmax)]`} id="expertise"><SectionLabel number="02">Our expertise</SectionLabel><div className="mt-[60px] mb-[75px] ml-[clamp(0px,8vw,130px)] grid items-end gap-[70px] min-[981px]:grid-cols-[1.35fr_.65fr] max-[980px]:ml-0 max-[680px]:mt-[45px] max-[680px]:mb-[50px] max-[680px]:gap-[25px]"><h2>Everything your business needs.<br /><em>Nothing it doesn’t.</em></h2><p className="mb-2 text-[15px] leading-[1.8] text-[#66718a]">Specialist expertise brought together around your business—not delivered in disconnected silos.</p></div><ServiceAccordion services={services} /></section>
    <section className="grid min-h-[740px] grid-cols-2 bg-g12-navy text-white max-[980px]:grid-cols-1" id="approach"><div className="relative min-h-[600px] overflow-hidden max-[980px]:min-h-[500px] max-[680px]:min-h-[380px]"><Image className="object-cover saturate-[.82] contrast-[1.06]" src="/images/live/perspective-advisory.jpg" alt="Senior financial advisors reviewing a business plan" fill sizes="(max-width: 800px) 100vw, 50vw" /><div className="absolute inset-0 bg-[linear-gradient(135deg,#020a1b14,#05183ab3)]" /><span className="absolute bottom-[3%] left-[8%] z-10 text-[clamp(90px,14vw,220px)] leading-[.8] font-bold tracking-[-.1em] text-white/[.1]">G12</span></div><div className="flex min-h-[620px] flex-col justify-center px-[clamp(40px,7vw,110px)] py-[105px] max-[680px]:min-h-[590px] max-[680px]:px-6 max-[680px]:py-[75px]"><SectionLabel number="03" light>The G12 perspective</SectionLabel><h2 className="mt-[60px] mb-[30px] [&_em]:text-[#a9c0f8] max-[680px]:mt-[45px]">Compliance is the baseline.<br /><em>Progress is the goal.</em></h2><p className="mb-[34px] leading-[1.8] text-white/65">We look beyond the numbers to understand what drives your business. That means commercially grounded advice, direct access to experienced professionals and solutions built around the decisions ahead.</p><Link className={outlineButtonClass} href="/about-us/">Why businesses choose us <span>↗</span></Link></div></section>
    <section className={`${sectionClass} relative overflow-hidden pb-[170px]`}><div className="absolute -right-[12vw] top-20 size-[430px] rounded-full bg-[#dbe6ff] blur-[2px]" aria-hidden="true" /><SectionLabel number="04">Built differently</SectionLabel><div className="relative mt-[90px] grid gap-x-[8vw] gap-y-20 min-[801px]:grid-cols-3">{[["01","Senior expertise,","personally involved.","Led by finance professionals with more than 18 years of hands-on advisory experience."],["02","One view of your","whole business.","Accounting, tax, audit, compliance and advisory connected under one trusted partner."],["03","Advice designed","for momentum.","We help you make smarter financial decisions, reduce friction and plan beyond the next deadline."]].map(([icon,line1,line2,text],index)=><article data-reveal className={`relative max-w-[330px] ${index===1?"min-[801px]:mt-24":""} ${index===2?"min-[801px]:mt-[-35px]":""}`} key={icon}><span className="font-serif text-[88px] leading-none text-g12-blue/10">{icon}</span><div className="mt-[-18px] h-2 w-2 rounded-full bg-g12-gold" /><h3 className="mt-8 mb-[22px] text-[clamp(27px,2.3vw,36px)] leading-[1.08] tracking-[-.04em] font-medium">{line1}<br />{line2}</h3><p className="text-sm leading-[1.8] text-[#66718a]">{text}</p></article>)}</div></section>
    <section className="relative overflow-hidden bg-white px-[max(24px,12vw)] py-[155px] text-center max-[680px]:py-[105px]"><div className="absolute left-1/2 top-1/2 size-[620px] -translate-x-1/2 -translate-y-1/2 rounded-full border border-g12-blue/10 shadow-[0_0_0_80px_rgba(36,71,168,.025),0_0_0_160px_rgba(36,71,168,.018)]" aria-hidden="true" /><blockquote data-reveal className="relative mx-auto max-w-[990px]"><span className="block font-serif text-[90px] leading-[.6] text-g12-gold">“</span><p className="font-serif text-[clamp(32px,4.2vw,60px)] leading-[1.14] tracking-[-.03em]">The strongest financial advice doesn’t only explain where you are. It gives you the confidence to decide <em className="text-g12-blue">where to go next.</em></p></blockquote><div className="relative mt-10 flex justify-center gap-[25px] text-[9px] uppercase tracking-[.13em] text-[#66718a] max-[680px]:flex-col max-[680px]:gap-2"><span>G12 Accounts</span><span>Strategic financial partner</span><span>UAE</span></div></section>
    <section className={`${sectionClass}`} id="insights"><SectionLabel number="05">Timely perspectives</SectionLabel><div className="mt-[60px] mb-[75px] grid items-end gap-[70px] min-[981px]:grid-cols-[1fr_auto] max-[980px]:mt-[45px] max-[980px]:mb-[50px] max-[980px]:gap-[25px]"><h2>Clarity for what’s<br /><em>coming next.</em></h2><Link className={textLinkClass} href="/insights/">View all insights <span>↗</span></Link></div><div className="grid items-start gap-[clamp(45px,8vw,120px)] max-[680px]:grid-cols-1 min-[681px]:grid-cols-[1.05fr_.95fr]"><article data-reveal><Link className="relative block aspect-[1.18] overflow-hidden rounded-[48%_48%_10%_10%/38%_38%_8%_8%] bg-g12-navy max-[680px]:aspect-[1.1]" href={insights[0].href}><Image className="object-cover transition-transform duration-700 hover:scale-[1.045]" src="/images/live/corporate-tax-advisory.jpg" alt="Corporate tax advisors reviewing financial information" fill sizes="(max-width: 680px) 100vw, 50vw" /></Link><div className="relative pt-8"><small className="text-[9px] font-bold uppercase tracking-[.1em] text-g12-blue">{insights[0].category} · {insights[0].time}</small><h3 className="mt-[15px] max-w-[560px] text-[clamp(24px,2.3vw,34px)] leading-[1.18] font-medium"><Link href={insights[0].href}>{insights[0].title}</Link></h3></div></article><div className="pt-[8vw] max-[680px]:pt-0">{insights.slice(1).map((insight,index)=><article data-reveal className="group relative py-8 pr-[55px] first:pt-0" key={insight.title}><span className="mb-5 block h-px w-full bg-[#07152f29] transition-all duration-500 group-hover:w-1/2 group-hover:bg-g12-blue" /><small className="text-[9px] font-bold uppercase tracking-[.1em] text-g12-blue">0{index+2} · {insight.category}</small><h3 className="mt-[15px] text-[clamp(21px,2vw,29px)] leading-[1.22] font-medium"><Link href={insight.href}>{insight.title}</Link></h3><Link className="absolute right-1 bottom-[34px] text-[22px] transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" aria-label={`Read ${insight.title}`} href={insight.href}>↗</Link></article>)}</div></div></section>
    <ContactBand email />
  </main></>;
}
