export type ContentPage = {
  slug: string;
  label: string;
  title: string;
  emphasis: string;
  description: string;
  body: string[];
  bullets?: string[];
  image?: string;
};

export const services: ContentPage[] = [
  { slug: "audit-assurance", label: "Audit & Assurance", title: "Confidence in every", emphasis: "number.", description: "Independent audit and assurance services that give leaders a clearer view of performance, risk and opportunity.", body: ["Our audit approach combines technical rigour with commercial understanding. We focus on the information that matters most to your business and communicate what it means clearly.", "From statutory audits to internal reviews, we help strengthen controls, improve reporting and build confidence with stakeholders."], bullets: ["Statutory audit", "Internal audit", "Financial review", "Agreed-upon procedures"], image: "/images/live/audit-assurance.jpg" },
  { slug: "compliance-services", label: "Compliance Services", title: "Controls that support", emphasis: "growth.", description: "Practical compliance and governance support built around the way your business operates.", body: ["Strong controls reduce friction and create a better foundation for growth. We help businesses understand their obligations, close gaps and keep compliance connected to commercial priorities."], bullets: ["Corporate governance", "Regulatory support", "Compliance reviews", "Internal controls"], image: "/images/live/compliance-services.jpg" },
  { slug: "corporate-tax", label: "Corporate Tax", title: "A clearer corporate tax", emphasis: "strategy.", description: "Strategic corporate tax advice and compliance support for businesses navigating the UAE tax landscape.", body: ["We help businesses understand their corporate tax position, meet filing obligations and make informed decisions as regulations evolve.", "Our advice is practical, commercially grounded and designed to support sustainable growth."], bullets: ["Tax registration & compliance", "Impact assessment", "Transfer pricing support", "Tax planning"], image: "/images/live/corporate-tax-advisory.jpg" },
  { slug: "customs-services", label: "Customs Services", title: "Make cross-border trade", emphasis: "simpler.", description: "Customs advisory that helps businesses manage duties, documentation and cross-border risk with confidence.", body: ["Our customs specialists bring clarity to import and export requirements, helping you reduce delays, manage exposure and make better trade decisions."], bullets: ["Customs advisory", "Duty optimisation", "Import and export support", "Classification reviews"], image: "/images/live/customs-services.jpg" },
  { slug: "international-tax", label: "International Tax", title: "Clarity across every", emphasis: "border.", description: "Cross-border tax planning and advisory for businesses operating across jurisdictions.", body: ["International growth brings opportunity and complexity. We connect UAE expertise with a wider view of tax treaties, structuring and compliance so decisions are made with the full picture in view."], bullets: ["Cross-border structuring", "Tax treaty advisory", "Global compliance", "Transfer pricing"], image: "/images/live/international-tax.jpg" },
  { slug: "vat", label: "VAT", title: "VAT support that keeps", emphasis: "business moving.", description: "End-to-end VAT registration, filing, compliance and advisory for UAE businesses.", body: ["We make VAT manageable with clear advice, disciplined processes and support that keeps pace with your business. Whether you are registering, filing or reviewing your position, we help reduce risk and uncertainty."], bullets: ["VAT registration", "Return filing", "Voluntary disclosure", "VAT health checks"], image: "/images/live/vat-services.jpg" },
];

export const posts: ContentPage[] = [
  { slug: "when-your-finance-function-needs-to-evolve", label: "Advisory", title: "When your finance function needs to", emphasis: "evolve.", description: "The signals that your finance function has outgrown its current shape—and what to do next.", body: ["A finance function should give leadership more than historical numbers. As a business grows, reporting, controls and decision support need to evolve with it.", "The right next step is usually a clearer view of the decisions the function must enable, followed by practical improvements to systems, ownership and reporting."] },
  { slug: "internal-controls-that-scale-with-growth", label: "Compliance", title: "Internal controls that scale with", emphasis: "growth.", description: "How to build controls that protect the business without slowing it down.", body: ["Effective controls are designed around real workflows, not added as paperwork after the fact. The best controls make responsibilities clear, surface exceptions early and support confident decisions."] },
  { slug: "transfer-pricing-understanding-how-business-works", label: "International Tax", title: "Transfer pricing starts with understanding how your", emphasis: "business works.", description: "A practical perspective on transfer pricing for growing UAE businesses.", body: ["Transfer pricing documentation is strongest when it reflects the commercial reality of the group. Understanding functions, assets and risks is the starting point for a defensible approach."] },
  { slug: "corporate-tax-strategy-that-supports-growth", label: "Corporate Tax", title: "Beyond compliance: building a corporate tax strategy that supports", emphasis: "growth.", description: "Corporate tax planning should support decisions, not simply record them.", body: ["A good corporate tax strategy connects compliance with the wider business plan. It helps leaders understand obligations early, identify risks and make better-informed growth decisions."] },
  { slug: "five-vat-risks-growing-businesses-overlook", label: "VAT", title: "Five VAT risks growing businesses often", emphasis: "overlook.", description: "Common VAT issues that can create avoidable cost and disruption.", body: ["Growth changes transaction flows, systems and responsibilities. Regular VAT reviews help businesses spot gaps before they become costly corrections or penalties."] },
  { slug: "what-better-management-reporting-can-unlock", label: "Advisory", title: "What better management reporting can", emphasis: "unlock.", description: "The right management reporting turns data into decisions.", body: ["Management reporting works when it answers the questions leaders actually need to ask. Clear measures, timely reporting and useful context create momentum across the business."] },
  { slug: "cross-border-growth-questions-to-ask-first", label: "International Tax", title: "Cross-border growth: the questions to ask", emphasis: "first.", description: "A starting framework for businesses planning international expansion.", body: ["Before entering a new market, businesses should understand the tax, legal, operational and reporting implications. Asking the right questions early keeps expansion deliberate."] },
  { slug: "prepare-finance-team-for-year-end-audit", label: "Audit", title: "Prepare your finance team for a smoother year-end", emphasis: "audit.", description: "Practical steps to improve audit readiness before year-end.", body: ["Audit readiness is built throughout the year. Clear reconciliations, supporting evidence and ownership of open items reduce last-minute pressure and improve the quality of the process."] },
  { slug: "cash-flow-forecasting-management-tool", label: "Advisory", title: "Cash-flow forecasting as a management", emphasis: "tool.", description: "Why cash-flow forecasting belongs at the centre of business decisions.", body: ["A forecast is most useful when it is current, owned and connected to actions. It gives leaders an early view of pressure points and the confidence to plan ahead."] },
  { slug: "corporate-tax-records-audit-ready-evidence-trail", label: "Corporate Tax", title: "Corporate tax records: creating an audit-ready", emphasis: "evidence trail.", description: "A disciplined records process makes tax compliance more reliable.", body: ["Good records explain how a number was reached, who reviewed it and where the supporting evidence sits. Building that trail early makes future compliance clearer and faster."] },
];

export const allContent = [...services, ...posts];
